### PR TITLE
Use glib-rs instead of gnome-class-shims

### PR DESCRIPTION
**Pull request by federicomenaquintero**
Basically the whole code generator is updated; we now use the glib-rs scheme of things, instead of gnome-class-shims.  The former is a superset of the latter, really.

The grammar is changed a bit for stylistic reasons, and also to add a Signal production.

This requires glib-rs out of my repository, as there is an outstanding PR there.  It should be merged soon.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@federicomenaquintero 

> This requires glib-rs out of my repository, as there is an outstanding PR there. It should be merged soon.

should I wait for that? Can you link to the PR?

**Comment by federicomenaquintero** [comment]
Sure, the glib-rs PR is https://github.com/gtk-rs/glib/pull/234.  I'll do some documentation updates there today and try to get it merged.

That PR depends on https://github.com/gtk-rs/gir/pull/459 (... actually, both PRs depend on each other; they are just for different repositories).

**Comment by federicomenaquintero** [comment]
It's fine to wait for the glib-rs PR to get merged; the new API should be fine, and it's only details in the gir implementation that may need changes.

**Comment by nikomatsakis** [comment]
@federicomenaquintero wait omg how has this not merged yet

**Pull request merged**
